--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ItzFel/ProperDuels
build-by-default: true
branches:
- master
projects:
  ProperDuels:
    libs:
      - src: Paroxity/Commando/Commando
        version: ^2.1.2
      - src: poggit/libasynql/libasynql
        version: ^3.3.1
    path: ""
...
